[workspace]
members = [
    "rustuna_core",
    "rustuna_sampler",
    "rustuna_storage",
    "rustuna_importance",
    "rustuna_js",
    "rustuna_pyo3",
]
resolver = "2"

[profile.release]
codegen-units = 1

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of Optuna"
repository = "https://github.com/optuna/rustuna"
keywords = ["machine-learning"]
categories = ["science"]
license = "MIT"

[workspace.dependencies]
rustuna_core = { path = "./rustuna_core" }
rustuna_sampler = { path = "./rustuna_sampler" }
rustuna_importance = { path = "./rustuna_importance" }
rustuna_storage = { path = "./rustuna_storage" }
rand = "0.8.5"
