[package]
name = "rustuna_pyo3"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lib]
name = "rustuna"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py311", "abi3t-py315", "extension-module"] }
rustuna_core = { workspace = true }
rustuna_sampler = { workspace = true }
rustuna_storage = { workspace = true }
rustuna_importance = { workspace = true }
