[build-system]
requires = ["maturin>=1.14,<2.0"]
build-backend = "maturin"

[project]
name = "rustuna"
description = "A faster Optuna implementation in Rust"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
version = "0.2.0.dev"

[project.urls]
homepage = "https://optuna.org/"
repository = "https://github.com/optuna/rustuna"
documentation = "https://rustuna.readthedocs.io"
bugtracker = "https://github.com/optuna/rustuna/issues"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "rustuna._rustuna"

[tool.uv]
exclude-newer = "5 days"
exclude-newer-package = { optuna = false }

[tool.ruff.lint]
select = ["E", "I"] # pycodestyle and isort
ignore = ["E501"]

[dependency-groups]
dev = [
    "optuna @ git+https://github.com/optuna/optuna.git@master",
    "cmaes",
    "ruff",
    "pytest",
    "maturin",
    "mypy",
    "freezegun",
    # test dependencies
    "matplotlib",
    "plotly",
    "scipy",
]
