name: Tests and checks (JavaScript)
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/checks_js.yml'
      - 'rustuna_js/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rustuna_core/src/**'

permissions:
  contents: read
jobs:
  js_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          target: wasm32-unknown-unknown
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: Installing biome.js
        working-directory: rustuna_js
        run: npm i -g biome
      - name: Lint
        working-directory: rustuna_js
        run: biome ci examples/*.ts test/*.mjs
      - name: Cache cargo binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-
      - name: Install wasm-bindgen-cli and wasm-opt
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 --locked | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          if ! command -v wasm-bindgen &> /dev/null || [ "$(wasm-bindgen --version | awk '{print $2}')" != "$WASM_BINDGEN_VERSION" ]; then
            cargo install wasm-bindgen-cli --version "$WASM_BINDGEN_VERSION" --force
          fi
          if ! command -v wasm-opt &> /dev/null; then
            cargo install wasm-opt
          fi
      - name: Build JS binding
        working-directory: rustuna_js
        run: ./build.sh
      - name: Run tsc
        working-directory: rustuna_js
        run: tsc --noEmit --project tsconfig.examples.json
      - name: Run tests
        working-directory: rustuna_js
        run: node --test
